project:
  type: website

website:
  title: "kasper munk rasmussen"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kmrasmussen/
      - icon: twitter
        href: https://x.com/chopwatercarry
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



