---
title: "How does static FC compare across sessions in MyConnectome Project?"
date: "2025-06-02"
categories: ["neuroscience", "fmri"]
---

One could imagine that one day it might be possible that a psychiatric patient could be undergoing some brain imaging sessions, and some computational model of the subject's brain will be used for guiding treatment.

MyConnectome Project has a lot of brain imaging recording from the same person. Perhaps it could be used as a playground to ask some questions about what possibilities and limitations there may be for this idea of making a personalized brain model for a patient.

# Formal notations for fMRI

A common object in computational analyses of fMRI is the functional connectivity matrix. Very simplified, fMRI gives you at each timepoint a 3d matrix $\omega_t \in \mathbb{R}^{W \times H \times D}$, describing "activity" at each coordinate. Therefore this $v_t$ is a quite high-dimensional object and is reduced by aggregating activity in different "brain areas".

We can think of $\Omega = [W] \times [H] \times [D]$ as the domain on which the original signal lives, where $[W] = \{0,...,W-1\}$.

Now each $v_t$, is a mapping $v_t : \Omega \to \mathbb{R}$, from each point in the domain to a value of activity.

This domain $\Omega$ obviously has some kind of structure, in some cases associate voxels with their Euclidean coordinates. This makes some sense, since we are considering $\Omega$ as the space of immediate signals. We might be trying to infer something about what the structure of the underlying brain state leading to a volume or a time series of volumes has been, but this brain state would then live in another space than the space of recorded volumes.


An "atlas" or "parcellation" is a partition of $\Omega$, a set of disjoint subsets. In some cases we might not require that the union of the sets constite $\Omega$, because what if some coordinate is outside the brain? We get a volume that is a box but the brain is not a box. We write $A_1, ..., A_N \subset \Omega$ of disjoint subsets $A_n$ of the domain. N will often be in the order of 100.

Now we can consider looking at a specific area, and consider only the parts of the signal in that area. $v_t^m : A_n \to \mathbb{R}$.
We can also consider the some method of aggregation: If an area $A_n$ has cardinality $|A_n|$, then we can consider a the set $\{v_t^n(\omega) \in \mathbb{R} | \forall \omega \in A_n \} \subseteq \mathbb{R}$, the set of all activities in that brain region at that time. One way of aggregating is to just take the mean, call it $\mu^n_t \in \mathbb{R}$.

Given some selection of an "atlas", we say that we *parcellate a recording* $\{v_t\}_{t\in[T]}$ by converting it to parcellated time series $\{\mu_t^n\}_{t\in [T],n\in[N]}$.

The parcellated time series constitute a reduced representation of the recording, in practice it will be a matrix $M \in \mathbb{R}^{T\times N}$.

One hopes that this object $M$ captures something meaningful about the brain recording, by averaging over the smaller activities, that the noise is thereby reduced.

One processing step that might be applied is to filter the frequencies. Since the our recording $v_t$ is made at discrete timesteps $t$, that are made every *TR* (repetition time) seconds in the real world, where TR is then the sampling interval. This and other details, make it so that there are principled reasons for doing frequency filtering of the time series. We will assume that $M$ is consisting of processed time series.

The basis of functional connectivity is to consider correlations between pairs $\mu_t^n$, $\mu_t^m$, for $m,n \in [N]$, using standard Pearson correlation. That is we consider them as vectors in $\mathbb{R}^T$.

For two vectors $x, y \in \mathbb{R}^T$, the Pearson correlation is the cosine distance between mean-centered versions. For two random variables $X$ and $Y$, the correlation is
$$
\text{Corr}(X,Y) = \frac{Cov(X,Y)}{\sqrt{Var(X)}\sqrt{Var(Y)}}
$$

and Pearson's rho is an 